import { Toaster } from 'react-hot-toast'
import { Navbar, Footer } from './components'
import { StateContext } from './context/StateContext'

import './globals.css'


export const metadata = {
  title: 'Apple store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="layout">
        <StateContext>
          <header>
            <Navbar />
          </header>
          <main className="main-container">
            <Toaster />
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </StateContext>
      </body>
    </html>
  )
}
