import { Navbar, Footer } from './components'
import { StateContext } from './context/StateContext'

// import { Inter } from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Apple store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className="layout">
        <StateContext>
          <header>
            <Navbar />
          </header>
          <main className="main-container">
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </StateContext>
      </body>
    </html>
  )
}
